## provide the name of the namespace
namespace:
  name: prod

## define the service parameters
service:
  port: 7111

image:
  pullPolicy: Always

## set the number of replicas for an application
replicaCount: 5

## define the resource parameters
resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"
