## provide the name of the namespace
namespace:
  name: staging

## define the service parameters
service:
  port: 5111



## set the number of replicas for an application
replicaCount: 3

## define the resource parameters
resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
